plugins:
  - babel
env:
  node: true
parser: babel-eslint
extends:
  - 'airbnb-base'
rules:
  no-console: 0
  space-before-function-paren: [1, { "anonymous": "ignore", "named": "always" }]
  no-underscore-dangle: [1, { "allowAfterThis": true }]
  class-methods-use-this: 0
  import/prefer-default-export: 0
  no-restricted-syntax: 0
  key-spacing: [1, { "beforeColon": false, "afterColon": true, "align": "value" }]
